### ISSUE TITLE
[FEA] Conda environment

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cusignal#13]
Other RAPIDS projects maintain separate conda environment files for different CUDA versions. cuSignal currently only specifies a range for cudatoolkit (>=9.2, <10.2).

And other RAPIDS projects do not include a separate file for Jetson (Are we going to officially support Jetson for cuSignal?).

We should decide whether to
- maintain separate conda environment files for different CUDA versions
- maintain a separate conda environment file for Jetson

and update the environment files accordingly.

**Comment by awthomp** [comment]
Since cuSignal currently heavily relies on CuPy, are you aware of any specific CUDA features in newer releases that are explicitly used? In other words, if we're on CuPy 7.0.0, we should enforce whatever CUDA version they rely on.

As for the Jetson Conda environment, many users of cuSignal are in the Software Defined Radio community where there's an interest in embedded platforms. I'd like to keep the dedicated conda environment here.

**Comment by seunghwak** [comment]
> are you aware of any specific CUDA features in newer releases that are explicitly used?

Nope, and I think this is not a big issue at this moment, but may become more relevant as we further integrate cuSignal with other RAPIDS projects.

> As for the Jetson Conda environment, ...

And same here, if cuSignal gets more and more dependent on other RAPIDS projects, support for embedded systems or Windows systems may become more difficult unless other RAPIDS projects cuSignal relies on also support embedded platforms or Windows systems. We may leave as is at this moment, but if we plan to further integrate cuSignal to other RAPIDS projects, I assume this needs to be discussed at the RAPIDS leadership level.

**Comment by BradReesWork** [comment]
cuSignal is slightly different than the other main RAPIDS efforts since currently purely Python.  As we expand cuSignal and if needed, add some low-level C/CUDA code, then am environment file per CUDA will be needed.  currently it is unnecessary

**Comment by awthomp** [comment]
Closing issue
