### ISSUE TITLE
[BUG] Resample Poly fails for n-dim arrays > 1 and upsample > 8

### ISSUE THREAD

**Issue by huazhixixi** [rapidsai/cusignal#295]
I am using resample_poly to process some data. However, when the up = 8, down = 1, it reports the following error.

<img width="1290" alt="图片" src="https://user-images.githubusercontent.com/59355161/101980611-93159b00-3ca1-11eb-859b-d97503bdfec8.png">

But when the up is lower than 8, the function works well.

The code is as below:
   **new_samples = cusignal.resample_poly(samples,8,1,axis=-1)**
The samples is a cupy array that on RTX 3090 with a cuda verison 11.1 and the shape of the samples is (2,131072)

Now, i have to use the resample_poly provided by the scipy package.

**Comment by awthomp** [comment]
Hi @huazhixixi. Thanks for the report. I've confirmed that this is a bug via the following code:

```python
import cupy as cp
import cusignal

sig = cp.random.rand(2, 131072)
cusignal.resample_poly(sig, 8, 1, window=('kaiser', 0.5), axis=1)
```

It seems the problem is doing a row-wise resample when ndim of the input signal is > 1 and upsample rate is > 8. @mnicely -- This probably has something to do with the block/grid CUDA dimensions???

As a work-around, though, please try the following and transpose the input/output data. This appears to work until we can get a fix.

```python
import cupy as cp
import cusignal

sig = cp.random.rand(2, 131072)
cusignal.resample_poly(sig.T, 8, 1, window=('kaiser', 0.5), axis=1).T
```

**Comment by awthomp** [comment]
Keeping issue open -- still need to address this bug report.

**Comment by awthomp** [comment]
Closed with https://github.com/rapidsai/cusignal/pull/335
