### ISSUE TITLE
[DOC] Why devide the sum(signal) in the 'cusignal/notebooks/api_guide/convolution_examples.ipynb' ?

### ISSUE THREAD

**Issue by vBaiCai** [rapidsai/cusignal#303]
## Report incorrect documentation

**Location of incorrect documentation**
cusignal/notebooks/api_guide/convolution_examples.ipynb
in **convolution section**.  

**Describe the problems or issues found in the documentation**

cconv = signal.convolve(sig, win, mode='same') / np.sum(sig)

**Steps taken to verify documentation is incorrect**

**Suggested fix for documentation**

I think, the `np.sum(sig)` may be a typo. In general，we normalize the convolved signal using `sum(win)` like [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve.html).  I can’t figure out why you devide the `sum(sig)` here.

## Report needed documentation

**Report needed documentation**

**Describe the documentation you'd like**
cconv = signal.convolve(sig, win, mode='same') / np.sum(win)

**Steps taken to search for needed documentation**

**Comment by awthomp** [comment]
Hey @vBaiCai -- thanks for the DOC report on cuSignal!

You're totally right: this is supposed to be `np.sum(win)` for the CPU portion and `cp.sum(win)` part. Looks like we have a typo in the CPU section (e.g using `np.sum(sig)` instead of `np.sum(win)`). Would you be willing to submit a PR? I am more than happy to guide you through the process!

**Comment by vBaiCai** [comment]
Yes, I'm willing to submit a PR.
