### ISSUE TITLE
[QST]Error while installing cuSignal in Windows 10

### ISSUE THREAD

**Issue by JulianaCenzi** [rapidsai/cusignal#410]
**What is your question?**
I am trying to install cuSignal in Windows 10. I've followed the instructions, but when I run ./build.sh, I get a error: '.' is not recognized as internal command....
Any thoughts?

**Comment by awthomp** [comment]
Hi @JulianaCenzi -- did you follow the CUDA on WSL instructions linked [here](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#abstract)? It sounds like you're not in a "Linux on Windows" shell since the `.` isn't recognized as a command. 

According to section 2.4 in the docs, you launch the linux distribution via:
`$ wsl.exe --list -v command`

**Comment by awthomp** [comment]
Going to close this issue, but feel free to reopen with more questions.
