### ISSUE TITLE
[QST] Package issues with Jupyter Notebook and Jetson

### ISSUE THREAD

**Issue by gpeyton** [rapidsai/cusignal#414]
I'm using a Jetson Nano and installed CuSignal as per instruction for aarch64. Also installed dependencies afterwards (numpy, scipy, pip and cupy). I manually installed jupyter using conda. 

When running an example notebook through SSH, I'm unable to import any modules, e.g.
`ModuleNotFoundError: No module named 'cupy'`

However, I am able to run python manually, import all the modules and run the same code. How do I resolve this? 

Thanks for the help!

**Comment by awthomp** [comment]
Hi @gpeyton, thanks for filing an issue, and I'm thrilled you're interested in cusignal.

A couple questions for you:
- It seems like you successfully compiled cusignal on the Nano from source. Is this correct? In a Python session on the Nano, you can import both cupy and cusignal?
- Are you trying to use the Nano as a Jupyter notebook server? Meaning you start your notebook on the Nano and try to connect to it via a different machine to run code?

If the above are both true, ensure you're in the right conda environment before launching the Jupyter notebook. For example, if you installed cusignal and its dependencies under the `cusignal-dev` environment, ensure that you're also running the notebook from this environment too.

After you ssh to the nano, just be sure you `source activate cusignal-dev` (or whatever you named your conda environment). Otherwise, you'll be in the 'base' conda environment, which probably isn't where you installed the libraries.

Hope this helps!

**Comment by gpeyton** [comment]
Thanks so much @awthomp - I forgot to activate the environment before running jupyter. That solved it!
